version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./dataset:/app/dataset
    environment:
      - NAME=sraEnv
      - ELASTICSEARCH_HOST=host.docker.internal # This will point to your host machine
      - ELASTICSEARCH_PORT=9200
