version: '3.9'

services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - esnet

  kib8:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kib8
    environment:
      - node.name=kib8
      - cluster.name=es-docker-cluster
      - elasticsearch.hosts=http://es8:9200
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - es8

volumes:
  data:
    driver: local

networks:
  esnet:
    driver: bridge
